# Generated by Django 5.1.4 on 2025-02-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
