# Generated by Django 5.1.4 on 2025-02-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_alter_careersform_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='careersform',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
