# Generated by Django 5.1.4 on 2025-04-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0036_remove_subcategory_bottom_padding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='specializedservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
