# Generated by Django 5.1.4 on 2025-04-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_blogentry_additional_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogbanner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
